baseURL = "https://reference.groupdocs.com/markdown"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://reference.groupdocs.com/?prefix=markdown/&region=us-west-2"


