baseURL = "/metadata"
title = "Groupdocs API References"
staticdir = 'content/sites/groupdocs/metadata/static'
enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["api-theme"]


[params.menu]
zh = "groupdocs-zh"
ru = "groupdocs-ru"
ar = "groupdocs-ar"
cs = "groupdocs-cs"
de = "groupdocs-de"
el = "groupdocs-el"
es = "groupdocs-es"
fr = "groupdocs-fr"
hi = "groupdocs-hi"
hu = "groupdocs-hu"
id = "groupdocs-id"
it = "groupdocs-it"
ja = "groupdocs-ja"
ko = "groupdocs-ko"
pl = "groupdocs-pl"
pt = "groupdocs-pt"
sv = "groupdocs-sv"
th = "groupdocs-th"
tr = "groupdocs-tr"
vi = "groupdocs-vi"
zh-hant = "groupdocs-zht"

defaultContentLang = 'en'
[languages]
  [languages.en]
    contentDir = 'content/sites/groupdocs/metadata/english'
    languageName = 'English'
	languageCode = "en"
    flag = "flag-us"
    weight = 10
  [languages.ru]
    contentDir = 'content/sites/groupdocs/metadata/russian'
    languageName = 'Русский'
    languageCode = "ru"
    flag = "flag-ru"
    weight = 11
  [languages.zh]
    contentDir = 'content/sites/groupdocs/metadata/chinese'
    languageName = "简体中文"
    languageCode = "zh"
    flag = "flag-cn"
    weight = 12


disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = ["(?i:readme.md)", '\.spin$']

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

[markup]
	[markup.tableOfContents]
		endLevel = 2
		ordered = true
		startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

# Everything below this are Site Params

[params]
copyright = "The groupdocs Authors"
privacy_policy = "https://policies.google.com/privacy"
topbar_search_active = false
logo_rel_link = ""

# Containerize Menu
[params.containerize]
menu = "groupdocs-en"

[params.meta]
msapplication_TileColor = "#2b5797"
msapplication_config = "https://cms.admin.containerize.com/templates/groupdocs/images/browserconfig.xml"
theme_color = "#ffffff"
author = "Groupdocs"

# Title of 404 page
title_404_page = "404 - Page Not Found | groupdocs API References"

# Open Grapgh settings
title = "groupdocs API References"
images = ["images/groupdocs-image-for-open-graph.jpg"]
description = "Class Libraries & REST APIs for the developers to manipulate & process Files from Word, Excel, PowerPoint, Visio, PDF, CAD & several other categories in Web, Desktop or Mobile apps. Develop & deploy on Windows, Linux, MacOS & Android platforms."

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false


[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false

[deployment]
[[deployment.matchers]]
# Set custom content type for /sitemap.xml
#pattern = "^sitemap\\.xml$"
#pattern = "^[a-z]\\.xml$"
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true

