baseURL = "https://reference.groupdocs.com/conversion"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://reference.groupdocs.com/?prefix=conversion/&region=us-west-2"


